create database PYTHON6;
GO
--TO OPEN DATABASE
USE	PYTHON6;
GO	

select * from INFORMATION_SCHEMA.TABLES
GO

CREATE TABLE STORES
(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
CITY VARCHAR(50) 
)

GO

SELECT * FROM STORES

INSERT INTO STORES(NAME,ADDRESS,CITY) VALUES('ARFAN MART','DHANMONDI','DHAKA')
INSERT INTO STORES(NAME,ADDRESS) VALUES('ARFAN MART','DHANMONDI')
INSERT INTO STORES(NAME,ADDRESS) VALUES('AFRIN MART','AZIMPUR')
INSERT INTO STORES  VALUES('AARONG','DINAJPUR','DINAJPUR')



GO

INSERT INTO STORES(NAME,ADDRESS,CITY) VALUES
('RAHIM STORE1','SHEWRA PARA1','DHAKA1'),
('RAHIM STORE2','SHEWRA PARA2','DHAKA2'),
('RAHIM STORE3','SHEWRA PARA3','DHAKA3');

SELECT ID,NAME,ADDRESS,CITY FROM STORES

SELECT NAME,CITY FROM STORES
SELECT * FROM STORES

SELECT * FROM STORES ORDER BY CITY ASC
SELECT * FROM STORES ORDER BY CITY DESC

SELECT * FROM STORES WHERE ID=7

SELECT * FROM STORES WHERE ID BETWEEN 3 AND 7
SELECT * FROM STORES WHERE ID IN (4,8)

SELECT * FROM STORES WHERE ID<4
SELECT * FROM STORES WHERE ID>=4

SELECT * FROM STORES WHERE ADDRESS LIKE 'D%'
SELECT * FROM STORES WHERE NAME LIKE '%T'

SELECT * FROM STORES WHERE ADDRESS LIKE '%D%'
SELECT * FROM STORES WHERE ADDRESS <> 'DINAJPUR'

SELECT * FROM STORES WHERE ID NOT IN (2,6)

SELECT * FROM STORES WHERE ADDRESS BETWEEN 'A' AND 'R'

SELECT * FROM STORES WHERE (ADDRESS BETWEEN 'A' AND 'R') AND CITY='DHAKA'

SELECT * FROM STORES WHERE (ADDRESS BETWEEN 'A' AND 'R') OR CITY='DHAKA'
SELECT * FROM STORES WHERE CITY IS NULL
SELECT * FROM STORES WHERE CITY IS NOT NULL

--UPDATE STORES SET NAME='AZIZ STORE' WHERE ID =4
--UPDATE STORES SET NAME='TAHMID MART' WHERE ID =7
--UPDATE STORES SET NAME='ESHA GENERAL STORE',CITY='BARISHAL' WHERE ID =8
--UPDATE STORES SET NAME='KADER GENERAL STORE',CITY='MYMENSHINGH' WHERE ID =9

--UPDATE STORES SET NAME='MOUSUMY MART',CITY='MUNSHIGONJ' WHERE CITY IS NULL

--DELETE STORES WHERE ID=2

--DROP TABLE STORES


--USE MASTER
--DROP DATABASE PYTHON6

--USE PYTHON6












